version: "3"
services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: marceloasf/nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - production_network
    depends_on:
      - "node1"
      - "node2"
      - "node3"

  mongodb:
    image: mongo
    networks:
      - production_network

  node1:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: marceloasf/alura-books
    container_name: alura-books1
    ports:
      - "3000"
    networks:
      - production_network
    depends_on:
      - "mongodb"
  node2:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: marceloasf/alura-books
    container_name: alura-books2
    ports:
      - "3000"
    networks:
      - production_network
    depends_on:
      - "mongodb"
  node3:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: marceloasf/alura-books
    container_name: alura-books3
    ports:
      - "3000"
    networks:
      - production_network
    depends_on:
      - "mongodb"

networks:
  production_network:
    driver: bridge
